学習管理アプリ課題
kenchan1979/learning_plan pull request #1
Opened 2021-12-14 05:03 UTC by kenchan1979

### カリキュラムURL
https://github.com/elites-team/2months_course/blob/master/doc/06_php/exercise_org/03_learning_plan/01.md

### 課題番号

### 現在の状況
cssでのレイアウト
完了、編集、削除ボタンの固定、画面幅が小さくなっても折り返さない。
display: flex;
flex-wrap: nowrap;

これらのボタンサイズの大きさの変更。
padding, widthの変更

等試したが上手くいかず。

html, phpでの
```
PHP の date 関数に対して表示方法を変更します。

<?= h(date('Y/m/d', strtotime($plan['****']))) ?>
```
ここをどう考えるか。

また、
```
* {
    margin: auto;
}
```
こちらは使ってはいけなかったような記憶があります。どうでしたでしょうか？

これらはどう考えれば良いのでしょうか？

### 期待していた動作

ボタンが折り返されない。ボタンのサイズの変更。

### 調べたこと・参考にしたURL
https://csshtml.work/button-size/
https://ics.media/entry/17522/

2021-12-14 05:30 UTC, kenchan1979 commented
![Screen Shot 2021-12-14 at 14 26 49](https://user-images.githubusercontent.com/80375718/145938589-9b45dea6-9f67-49b5-8672-34c4d773dc31.png)

こちらです。ボタンが折り返され、かつ、大きさも小さいままです。どこの詳細度が高いかわかりません😅
また、レスポンシブ対応の方はまだ作れていません。

確認お願いします😄

2021-12-14 05:39 UTC, kazu-taka requested changes
@kenchan1979 
スクリーンしょっとありがとうございます！
ちなみに幅はどのくらいでしょうか！？
課題の方も800px以下ににあると同じように折り返す可能性があるので、一旦800
pxより広い幅で確認お願いします😊

2021-12-14 05:39 UTC, kazu-taka commented on style.css
> +.btn {
@kenchan1979 
ボタンはaタグで作成されているので、幅を広げる場合はdisplayをblock要素に変更してあげる必要があります✨
block要素にへんこうすることで、padding等を指定することが可能です✨

2021-12-14 07:48 UTC, kenchan1979 commented
![Screen Shot 2021-12-14 at 16 44 07](https://user-images.githubusercontent.com/80375718/145954902-41c653b2-080e-4c82-b6d4-bf57c659d693.png)

両方向で今のindex.phpのコードをほぼほぼ変えないで縛りたいのですが、どうすれば良いですか？

2021-12-14 07:56 UTC, kazu-taka commented
@kenchan1979 
縛りたいというのはどのような状態でしょうか！？
スクリーンショットを見る限りだと特に問題ないように思えます✨

2021-12-14 08:03 UTC, kenchan1979 commented
現段階だと実際には学習内容、完了期限、完了・編集・削除ボタンが横一列に並んでいるように見えますが、悪く言えば帳尻を合わせて見せているだけで数が増えた場合、少しずつズレて来てしまう状態です。
先程の指紋でdisplayをblockとinline-blockに変えて試しました。blockだとレイアウトがだいぶズレてしまったのでinline-blockに現在設定している状態です💦

2021-12-14 08:10 UTC, kazu-taka commented
なるほど！！
先程の未達成のようなエリアはtableタグを使用すると綺麗に並べる事が可能です✨
https://creive.me/archives/9986/

2021-12-14 09:57 UTC, kenchan1979 commented
```
 <div class="incomplete-area bg">
            <h2 class="sub-title">未達成</h2>
            <hr>
            <table class="plan-list">
                <thead>
                    <tr>
                        <th class="plan-title">学習内容</th>
                        <th class="plan-due-date">完了期限</th>
                        <ul>
                            <?php foreach ($notyet_learnings as $learning) : ?>
                                <li>
                                    <th class="done-link-area"><a href="done.php?id=<?= h($learning['id']) ?>" class="btn done-btn">完了</a></th>
                                    <th class="edit-link-area"><a href="edit.php?id=<?= h($learning['id']) ?>" class="btn edit-btn">編集</a></th>
                                    <th class="delete-link-area"><a href="delete.php?id=<?= h($learning['id']) ?>" class="btn delete-btn">削除</a></th>
                                </li>
                            <?php endforeach; ?>
                        </ul><br>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <?php foreach ($notyet_learnings as $learning) : ?>
                            <td>
                                <?= h($learning['title']) ?>
                            </td>
                        <?php endforeach; ?>
                        <?php foreach ($notyet_learnings as $learning) : ?>
                            <?php if (date("Y-m-d") >= h($learning['due_date'])) : ?>
                                <td>
                                    <div class="rdate"><?= h($learning['due_date']) ?></div>
                                </td>
                            <?php else : ?>
                                <td>
                                    <div class="date"><?= h($learning['due_date']) ?></div>
                                </td>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </tr>
                </tbody>
            </table>
        </div>
```
未達成のtableを使った書き方はこんな感じで良いのでしょうか？もしこのやり方でよければ後はcssで整理していくのでしょうか？ただ、この書き方だと、ボタンが３つずつで改行できませんでした。br や　”＼n˜ 等を使ったのですが💦

2021-12-14 10:44 UTC, kazu-taka commented
@kenchan1979 
tdタグの中には色々なタグを複数入れても問題ないですよ😊
ボタンを3つ表示させたいのであれば、tdタグの中に3つ入れるのが良いと思います✨

2021-12-14 13:22 UTC, kenchan1979 commented
```
                     <tr class="incomplete">
                            <td>
                                <?php foreach ($notyet_learnings as $learning) : ?>
                                    <div class="content"><?= h($learning['title']) ?></div>
                                <?php endforeach; ?>
                            </td>
                            <td>
                                <?php foreach ($notyet_learnings as $learning) : ?>
                                    <?php if (date("Y-m-d") >= h($learning['due_date'])) : ?>
                                        <div class="reddate"><?= h($learning['due_date']) ?></div>
                                    <?php else : ?>
                                        <div class="date"><?= h($learning['due_date']) ?></div>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </td>
                            <td>
                                <?php foreach ($notyet_learnings as $learning) : ?>
                                    <div class="choice-btn">
                                        <a href="done.php?id=<?= h($learning['id']) ?>" class="btn done-btn">完了</a></th>
                                        <a href="edit.php?id=<?= h($learning['id']) ?>" class="btn edit-btn">編集</a></th>
                                        <a href="delete.php?id=<?= h($learning['id']) ?>" class="btn delete-btn">削除</a></th><br>
                                    </div>
                                <?php endforeach; ?>
                            </td>
                        </tr>
```
```
.incomplete {
    display: flex;
    flex-wrap: nowrap;
    justify-content: space-between;
}
```
htmlの教科書p155辺りにもありますが、これで子要素が真ん中と両端によるという認識だと違いますか？
space-betweenが効いてくれません。
また、こんな記事も見つけました。
https://qiita.com/ke_na/items/07998f5b3bea586f5655

https://user-images.githubusercontent.com/80375718/146006233-7132f010-5407-475b-82bc-165fb2341646.mov

2021-12-14 21:21 UTC, kazu-taka commented
@kenchan1979 
trタグの中の要素のtdタグは最初から横並びになるので、display: flex関連の指定はなくても大丈夫です✨
親要素の`incomplete-area`に`width: 100%`を指定してもうまくいかないですかね！？😊

2021-12-15 04:32 UTC, kenchan1979 commented
```
 <div class="incomplete-area bg">
            <h2 class="sub-title">未達成</h2>
            <hr>
            <table class="plan-list">
                <tbody>
                    <tr class="incomplete">
                        <td>
                            <div class="plan-title">学習内容</div>
                            <?php foreach ($notyet_learnings as $learning) : ?>
                                <div class="content"><?= h($learning['title']) ?></div>
                            <?php endforeach; ?>
                        </td>
                        <td>
                            <div class="plan-due-date">完了期限</div>
                            <?php foreach ($notyet_learnings as $learning) : ?>
                                <?php if (date("Y-m-d") >= h($learning['due_date'])) : ?>
                                    <div class="date reddate"><?= h($learning['due_date']) ?></div>
                                <?php else : ?>
                                    <div class="date"><?= h($learning['due_date']) ?></div>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </td>
                        <td>
                            <br>
                            <div class="choice-btn">
                                <?php foreach ($notyet_learnings as $learning) : ?>
                                    <!-- <div class="choice-btn"> -->
                                    <a href="done.php?id=<?= h($learning['id']) ?>" class="btn done-btn">完了</a>
                                    <a href="edit.php?id=<?= h($learning['id']) ?>" class="btn edit-btn">編集</a>
                                    <a href="delete.php?id=<?= h($learning['id']) ?>" class="btn delete-btn">削除</a><br>
                                    <!-- </div> -->
                                <?php endforeach; ?>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
```
td内で学習内容と中身の表示を左の行頭で合わせたいのですが、text-align: left; を使っても動きません。
どう考えれば良いでしょうか？

2021-12-15 11:25 UTC, kzri4 commented
git clone してきて確認したのですが、こちらでは640pxくらいで以下の画像のとおりだったので、添付してくださった画像のようにならないので、具体的にどうなるか再度動画でいただければと思います！


![スクリーンショット 2021-12-15 19 59 50](https://user-images.githubusercontent.com/68971142/146174677-ac226fe6-844c-465b-9366-4375e38e503c.png)

2021-12-15 11:50 UTC, kzri4 commented
これだとどうですかね？

```
                        <tr>
                            <td><a href="done.php?id=<?= h($learning['id']) ?>" class="btn done-btn">完了</a></td>
                            <td><a href="edit.php?id=<?= h($learning['id']) ?>" class="btn edit-btn">編集</a></td>
                            <td><a href="delete.php?id=<?= h($learning['id']) ?>" class="btn delete-btn">削除</a></td>
                        </tr>
```

2021-12-15 13:50 UTC, kenchan1979 commented
リスポンシブ対応画面は800px以下と600px以下対応になっていますが、600px以下の方は何pxまでという認識なのでしょうか？また、課題の画像を見ると未達成、完了のところで左の学習内容だけ折り返されていますので、先程の質問同様、真ん中、右はwhite-space:nowrap;で固定しています。ですが、左の折り返し部分に来ると左だけ上に移動してしまいます。800px以下までのは作りましたが、左の部分は折り返されていません。理屈的にはmargin特に縦方向が動くと思うのでautoとかに設定して解決するかと思って色々試しましたがダメです💦どう解決すれば良いですか？

https://user-images.githubusercontent.com/80375718/146198299-6c36f77f-7e60-44bd-86a2-de123142df3c.mov

2021-12-16 04:01 UTC, Arisaarisa commented
課題提出お疲れ様です！表示とてもキレイになりましたね✨
システムの動きがまだうまくいってないところがあるようなので修正お願いします🙏

【未達成エリア】
- 現在未達成エリアの順番が入力した順になってしまうと思うので、'期限日の昇順でデータを表示'されるようにしてみてください😃
【完了エリア】
- 完了エリアは'完了日の降順でデータ表示'されるようにしてください✨
- 未完了ボタンを押しても未達成エリアに移動しないので登録内容が未達成エリアに移動するようにしてください。
（例えば、現在update_status_to_done関数とno_yet関数を定義していると思いますが完了と未完了の関数は同じものを使用できるようにもできます。if文の中でis_nullを使い変数がtureかfalseか振り分けます。）

2021-12-16 04:36 UTC, Arisaarisa commented
こちらがまだできていないようなので修正お願いします🙏
【未達成エリア】

現在未達成エリアの順番が入力した順になってしまうと思うので、'期限日の昇順でデータを表示'されるようにしてみてください😃

2021-12-17 02:36 UTC, kazu-taka requested changes
@kenchan1979 
１点修正お願いします🙏
他は問題なさそうな気がしますが、もし他に気になるところがなければ、ドラフトの通常のプルリクエストに修正お願いします😊

2021-12-17 02:36 UTC, kazu-taka commented on functions.php
> +    // ORDER BY :due_date ASC
@kenchan1979 
不要なコメントは削除お願いします✨

2021-12-17 03:13 UTC, merged